testing todo check

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,4 +1,4 @@
-name: Python Tox Multiplatform CI
+name: Test
 
 on:
   push:
@@ -7,6 +7,8 @@ on:
   pull_request:
     branches:
       - "action-playground-main"
+
+  workflow_dispatch:
 
 jobs:
   build:
@@ -27,8 +29,19 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
 
-      - name: Install dependencies
-        run: poetry install
-        
-      - name: Test with tox
-        run: poetry run tox
+      # - name: Install dependencies
+      #   run: poetry install
+
+      # - name: Test with tox
+      #   run: poetry run tox
+
+      - name: TODO Check
+        run: |
+          directory_to_scan="./"
+          todo_regex="TODO:(?!\s*\[[A-Za-z0-9-]+\])"
+          result=$(find "$directory_to_scan" -type f -name "*.py" -exec grep -Hn -P "$todo_regex" {} \);
+
+          if [ -n "$result" ]; then
+            echo "Non-matching TODO comments found:"
+            exit 1  # Fail the workflow
+          fi
